name: cmake

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ubuntu-22-04:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-x86_64, win32, win64, pluginval]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          dpf_path: .
          suffix: _22_04
          target: ${{ matrix.target }}

  ubuntu-24-04:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-x86_64, pluginval]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          dpf_path: .
          suffix: _24_04
          target: ${{ matrix.target }}

  macos-13:
    strategy:
      matrix:
        target: [macos-intel, macos-universal, macos-10.15]
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          dpf_path: .
          suffix: _13
          target: ${{ matrix.target }}

  macos-14:
    strategy:
      matrix:
        target: [macos-intel, macos-universal, macos-10.15]
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          dpf_path: .
          suffix: _14
          target: ${{ matrix.target }}

  macos-15:
    strategy:
      matrix:
        target: [macos-intel, macos-universal, macos-10.15]
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          dpf_path: .
          suffix: _15
          target: ${{ matrix.target }}

  msvc-win32:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure
      run: |
       cmake -S . -B build -G"Visual Studio 17 2022" -A"Win32" -DCMAKE_BUILD_TYPE="Release"
    - name: Build
      run: cmake --build build --config "Release" -j 2
    - name: Show built files
      working-directory: build/bin
      run: tree
    - uses: actions/upload-artifact@v4
      with:
        name: msvc-win32
        path: build/bin/

  msvc-win64:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure CMake
      run: |
       cmake -S . -B build -G"Visual Studio 17 2022" -A"x64" -DCMAKE_BUILD_TYPE="Release"
    - name: Build all
      working-directory: build
      run: cmake --build . --config "Release" -j 2
    - name: Show built files
      working-directory: build/bin
      run: tree
    - uses: actions/upload-artifact@v4
      with:
        name: msvc-win64
        path: build/bin/

  msvc-arm64:
    runs-on: windows-11-arm
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Configure CMake
      run: |
       cmake -S . -B build -G"Visual Studio 17 2022" -A"ARM64" -DCMAKE_BUILD_TYPE="Release"
    - name: Build all
      working-directory: build
      run: cmake --build . --config "Release" -j 2
    - name: Show built files
      working-directory: build/bin
      run: tree
    - uses: actions/upload-artifact@v4
      with:
        name: msvc-arm64
        path: build/bin/
